-- MySQL Script generated by MySQL Workbench
-- Fri 22 Jan 2021 06:54:29 AM -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema epico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema epico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epico` DEFAULT CHARACTER SET utf8 ;
USE `epico` ;

-- -----------------------------------------------------
-- Table `epico`.`epico_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epico`.`epico_items` (
  `iditems` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `cost_price` DECIMAL(15,2) NOT NULL,
  `unit_price` DECIMAL(15,2) NOT NULL,
  `pic_filename` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iditems`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
